-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE A
# WHERE 
#     SELECT USER_ID, PRODUCT_ID
#     FROM ONLINE_SALE B
#     WHERE B.
# ORDER BY USER_ID, PRODUCT_ID DESC;

SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS purchase_count
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING purchase_count > 1
) AS RepeatedPurchases
ORDER BY USER_ID ASC, PRODUCT_ID DESC;
