-- 코드를 작성해주세요
SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM ITEM_INFO I1, ITEM_INFO I2, ITEM_TREE T
WHERE I1.RARITY = 'RARE' AND I1.ITEM_ID = T.PARENT_ITEM_ID AND I2.ITEM_ID = T.ITEM_ID
ORDER BY I2.ITEM_ID DESC