-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH 
FROM FISH_INFO FI, FISH_NAME_INFO FNI
WHERE FI.FISH_TYPE = FNI.FISH_TYPE AND (FI.FISH_TYPE, FI.LENGTH) IN
(SELECT FISH_TYPE, MAX(LENGTH)
FROM FISH_INFO
GROUP BY FISH_TYPE)