-- 코드를 입력하세요
SELECT TITLE, BD.BOARD_ID, REPLY_ID, RY.WRITER_ID, RY.CONTENTS, DATE_FORMAT(RY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD BD, USED_GOODS_REPLY RY
WHERE BD.BOARD_ID = RY.BOARD_ID AND YEAR(BD.CREATED_DATE) = 2022 AND MONTH(BD.CREATED_DATE) = 10
ORDER BY RY.CREATED_DATE ASC, BD.TITLE ASC